
function testImageFormat(format,data,callback){let img=new Image();img.onload=img.onerror=()=>{callback(img.height===2);};img.src=data;}
function isAvif(){testImageFormat("avif","data:image/avif;base64,AAAAIGZ0eXBhdmlmAAAAAG1pZjFhdmlmAAAAAGF2MDFtZGF0EgAKBQAACQAAAD1iGQ==",(support)=>{let className=support?"avif":"no-avif";document.documentElement.classList.add(className);});}
function isWebp(){testImageFormat("webp","data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA",(support)=>{let className=support?"webp":"no-webp";document.documentElement.classList.add(className);});};function isDevice(){let isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};if(isMobile.any()){document.body.classList.add("_touch");}else{document.body.classList.add("_pc");}}
isDevice();function scrollHeader(){const header=document.querySelector('.cl-header');const headerHeight=header.offsetHeight;function onScroll(){if(window.scrollY>headerHeight/2){header.classList.add('cl-scroll');}else{header.classList.remove('cl-scroll');}}
onScroll();window.addEventListener('scroll',onScroll);}
scrollHeader();document.querySelectorAll('[data-tabs]').forEach(parent=>{const buttons=parent.querySelectorAll('[data-tab-btn]');const results=parent.querySelectorAll('[data-tab]');buttons.forEach(button=>{const tabName=button.dataset.tabBtn;button.addEventListener('click',()=>{buttons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');results.forEach(block=>{if(block.dataset.tab===tabName){block.classList.add('active');}else{block.classList.remove('active');}});});});});;isAvif();isWebp();isDevice();function handleTickInit(tick){tick.value=0;const observer=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){tick.value=12345678;observer.unobserve(entry.target);}});},{threshold:0.5});observer.observe(document.getElementById('counter'));}
$(function(){$('[data-toggle="popover"]').popover();});const containers=document.querySelectorAll('.cl-hero__point-imgs');let canSwitch=true;containers.forEach(container=>{const cards=container.querySelectorAll('.cl-card');cards.forEach(card=>{card.addEventListener('mouseenter',()=>{if(!canSwitch){return;}
canSwitch=false;const order=Number(card.dataset.order);if(isNaN(order)||order===0){canSwitch=true;return;}
card.dataset.order=0;cards.forEach(c=>{if(c!==card&&c.dataset.order!=='2'){c.dataset.order=Number(c.dataset.order)+1;}
c.style.transform=`translate(${50 * (Number(c.dataset.order) - 1)}%, -50%)`;c.style.zIndex=cards.length-c.dataset.order;});setTimeout(()=>{canSwitch=true;},1000);});});});const dots=document.querySelectorAll('.cl-hero__point-button');dots.forEach(dot=>{dot.addEventListener('click',()=>{const parent=dot.offsetParent;const win=parent.querySelector('.cl-hero__point-window');const winCoords=win.getBoundingClientRect();console.log(winCoords);if(winCoords.right>window.innerWidth){win.style.right=`-25px`;win.style.left='auto';win.style.transform='none';}else if(winCoords.left<0){win.style.left=`-25px`;win.style.right='auto';win.style.transform='none';}
win.classList.add('active');});});window.addEventListener('click',e=>{document.querySelectorAll('.cl-hero__point-window').forEach(win=>{if(!e.target.closest('.cl-hero__point')||win.closest('.cl-hero__point')!==e.target.closest('.cl-hero__point')){win.classList.remove('active');}});});let slideChangeCounter=0;const carousels=['#carouselExampleControls','#carouselExampleControls2','#carouselExampleControls3','#carouselExampleControls4','#carouselExampleControls5','#carouselExampleControls6'];carousels.forEach(selector=>{$(selector).on('slid.bs.carousel',function(e){slideChangeCounter++;if(slideChangeCounter>=5){$('#registerModal').modal('show');slideChangeCounter=0;}});});;